language: node_js
node_js:
  - "6"
  - "8"
cache: npm
install:
    - npm install
    - npm install -g codecov
script: 
    - npm run test
    - npm run coverage
    - npm run report-coverage
    - codecov
sudo: false
jobs:
    include:
        - stage: release
          node_js: lts/*
          script: npm run build
          deploy:
              provider: script
              email: "$NPM_EMAIL"
              skip_cleanup: true
              script:
                  - npx semantic-release


